# SPDX-FileCopyrightText: 2019-2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0

version: '3.4'
services:
  orgviewer:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      GLOBAL_API_URL: http://localhost:5000
      GLOBAL_API_ROOT_UUID: "f06ee470-9f17-566f-acbe-e938112d46d9"
      # Loenorganisation
      # GLOBAL_API_ROOT_UUID: "fb2d158f-114e-5f67-8365-2c520cf10b58"
      # GLOBAL_ORG_PERSON_RELATION: "association"

      GLOBAL_ORG_UNIT_HIERARCHY_UUIDS:
      # GLOBAL_APP_TITLE: "Andeby Kommune"
      # GLOBAL_ORG_PERSON_RELATION: "engagement"
      # VUE_APP_TREE_LAYOUT: "hybrid"
      # VUE_APP_LOGO_PATH: "https://frederikshavn.dk/Resources/images/frk_logo_blue.svg"
      # VUE_APP_HIDE_ORG_UNIT_UUIDS:
      # VUE_APP_HIDE_MANAGER_ORG_UNITS: "true"
      # VUE_APP_HIDE_ORG_UNIT_LEVELS: '["abbbefb2-85a6-4a5d-ad94-98a363adfee6", "418b313a-979f-4a26-807e-ba8dd3114d74"]'
      # VUE_APP_USE_AUTOCOMPLETE_API: "true"
      # VUE_APP_SORT_SPECIFIC_UNITS_SILKEBORG: "true"
      # VUE_APP_SHOW_EXTENSION_2_VIBORG: "true"
      # VUE_APP_REMOVE_ORG_UNIT_EMAIL: "true"
      # VUE_APP_REMOVE_PERSON_COUNT: "true"
      # VUE_APP_REMOVE_CHILDREN_COUNT: "true"
      # VUE_APP_REMOVE_ENGAGEMENT_TYPE_UUID: "8acc5743-044b-4c82-9bb9-4e572d82b524"
      KEYCLOAK_CLIENT_SECRET: "30303030-3030-3030-3030-303030303030"
      # VUE_APP_FAVICON_PATH: "https://frederikshavn.dk/Resources/images/favicon.ico"
      # VUE_APP_THEME_CSS: "frederikshavn.custom.css"

    ports:
      - "8083:80"
